spring:
  jpa:
    hibernate:
      ddl-auto: ${ddl-auto}
    properties:
      hibernate.format_sql: ${format_sql}
      hibernate.dialect: ${dialect}
  datasource:
    url: ${url}
    username: ${username}
    password: ${password}
  application:
    name: GetUserDetails