spring:
  jpa:
    hibernate:
      ddl-auto: ${ddl-auto}
    properties:
      hibernate.format_sql: ${format_sql}
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: ${url}
    username: ${username}
    password: ${password}
